-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, SUM(b.SALES_AMOUNT * a.PRICE) AS SALES
FROM PRODUCT a 
    JOIN (SELECT PRODUCT_ID, SALES_AMOUNT
        FROM OFFLINE_SALE) b ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY 1
ORDER BY 2 DESC, 1