-- 코드를 작성해주세요
SELECT ID, 
    CASE WHEN a.R <= (a.C * 0.25) THEN 'CRITICAL'
    WHEN a.R <= (a.C * 0.50) THEN 'HIGH'
    WHEN a.R <= (a.C * 0.75) THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R, COUNT(*) OVER () AS C
     FROM ECOLI_DATA) a
ORDER BY 1