-- 코드를 작성해주세요


SELECT s.SCORE AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
    JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO) s ON e.EMP_NO = s.EMP_NO
ORDER BY 1 DESC
LIMIT 1